CREATE TABLE public."Specifications"
(
url character varying COLLATE pg_catalog."default",
language character varying COLLATE pg_catalog."default",
job_title character varying COLLATE pg_catalog."default",
job_location character varying COLLATE pg_catalog."default",
company_name character varying COLLATE pg_catalog."default",
"Job_Id" bigint NOT NULL,
"ID" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
job_ad_duration character varying COLLATE pg_catalog."default",
job_applications character varying COLLATE pg_catalog."default",
seniority_level character varying COLLATE pg_catalog."default",
industry character varying COLLATE pg_catalog."default",
employment_type character varying COLLATE pg_catalog."default",
job_functions text COLLATE pg_catalog."default",
job_text text COLLATE pg_catalog."default",
date_added timestamp without time zone,
date_scraped timestamp without time zone,
CONSTRAINT "Specifications_pkey" PRIMARY KEY ("ID")
)

TABLESPACE pg_default;

ALTER TABLE public."Specifications"
OWNER to postgres;
